# Generated by Django 5.2.4 on 2025-08-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_user_order_ticket_alter_movie_actors_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
